# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/cudf/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/cusignal/labels

Python:
  - python/**
  - notebooks/**

CMake:
  - '**/CMakeLists.txt'
  - '**/cmake/**'
  
cpp:
  - cpp/**

conda:
  - conda/**

ci:
  - /ci/**

github:
  - .github/**
  
docker:
  - '**/Dockerfile'
  - '**/.dockerignore'
  - docker/**
